// JavaScript Document
window.noticias=new Array();
window.onload=cargarNoticias()

function cargarNoticias(){
	window.noticias[2]={titulo:"Torneo Apertura 2015 del Futbol Intercountry (AIF)", foto:"img/productos/futbol.jpg", resumen:"Este fin de semana arranca la temporada de futbol intercountry, te esperamos para que te anotes asi podes jugar esta temporada.",  descript:"Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.", qr:"img/qr/qr.jpg", plus:"Este producto no tiene plus"};
	window.noticias[1]={titulo:"Gran torneo Padres e Hijos + almuerzo en familia", foto:"img/productos/golf.jpg", resumen:"Sabado 18/8 Torneo en la cancha 9, inscripciones abiertas",  descript:"Aca va la noticia, con los detalles de la misma, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore. olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.", qr:"img/qr/qr.jpg", plus:"Este producto no tiene plus"};
	window.noticias[0]={titulo:"comienza el Abierto de polo Tortugas 2015. Venta de Entradas para todos los partidos.", foto:"img/productos/polo.jpg", resumen:"Conozca los partidos que se vienen, horarios y demas",  descript:"Aca va la noticia, con los detalles de la misma, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore. olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.", qr:"img/qr/qr.jpg", plus:"Este producto no tiene plus"};
	window.noticias[3]={titulo:"Oportunidad en Penn Atp Citenis Circuito Intercountry", foto:"img/productos/padel.jpg", resumen:"Todos los sabados y domingos, clases gratis a las 16Hs",  descript:"Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, consectetur tempor incididunt ut labore et dolore.", qr:"img/qr/qr.jpg", plus:"Este producto no tiene plus"};
	window.noticias[4]={titulo:"Entrega de Premios para sub 20 - Tenis y Padel!", foto:"img/productos/premios.jpg", resumen:"Entrega de premios en el house principal",  descript:"Aca va la noticia, con los detalles de la misma, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore. olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.", qr:"img/qr/qr.jpg", plus:"Este producto no tiene plus"};
	window.noticias[5]={titulo:"Comienza el Circuito verano 2015 - Paleta y Squash! ", foto:"img/productos/squash.jpg", resumen:"Se viene el torneo de squash interno, no olvides que tenes hasta el 20/8 para anotarte",  descript:"Aca va la noticia, con los detalles de la misma, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore. olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore olor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et doloreolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.Aca va alguna descripci&oacute;n del producto, Lorem ipsum dolor sit amet, do eiusmod tempor incididunt ut labore et dolore.", qr:"img/qr/qr.jpg", plus:"Este producto no tiene plus"};
	
	mostrarNoticias();
}
function mostrarNoticias(){
	//alert("Entre a agregar agenda");
	if(document.getElementById("contiene_noticias")!=null){
	var texto=" ";
	var primero=0;
	for (var b in window.noticias){ 
	
		if(primero!=0){
	   texto +='<div class="noticias" onclick="openNoticia('+b+')"><div class="not_img" style="background-image:url('+window.noticias[b].foto+');"></div><div class="titulo" > '+window.noticias[b].titulo+'</div><div class="copete">'+window.noticias[b].resumen+'</div></div><div class="separador"></div>';
	   }else{
		   primero=1;
		   texto +='<div class="noticias" onclick="openNoticia('+b+')"><div class="primera_titulo" > '+window.noticias[b].titulo+'</div><div class="primera_img" style="background-image:url('+window.noticias[b].foto+');"></div></div><div class="separador"></div>';
   }
   }
   document.getElementById("contiene_noticias").innerHTML=texto;}
	else{ setTimeout(function(){mostrarNoticias();},50);}
}
function openNoticia(cual){
	texto='<div class="header"><div class="titulo">NOVEDADES<a href="#"><img class="i" src="img/I.jpg" width="25" height="25" /></a></div></div><div class="contenidos"><div class="contenedor_fondo" style="background-image:url('+window.noticias[cual].foto+');"></div><div class="corredor_noticia"><div class="noticia"><H1>'+window.noticias[cual].titulo+'</H1><H3>'+window.noticias[cual].resumen+'</H3><div class="texto">'+window.noticias[cual].descript+'</div></div></div> <!--        CALENDARIO / RELOJ      --></div><div class="footer" style="z-index:25;"><a onclick="cerrarPopUp();"><img src="img/cerrar.png" width="135" height="135" /></a></div>';
	//texto='<div class="scroll"><div class="titulo"><p>'+window.noticias[cual].titulo+'</p></div><img src="'+window.noticias[cual].foto+'" class="ppal" /><div class="content"><p>Noticia: <span>'+window.noticias[cual].descript+'</span></p></div></div><div class="botones"><div onclick="cerrarPopUp();" class="boton_unico aceptar"><p>ACEPTAR</p></div></div>';
	document.getElementById("cartelNoticias").innerHTML=texto;
	document.getElementById("cartelNoticias").style.visibility="visible";
	document.getElementById("fondo_negro").style.visibility="visible";
}
function cerrarPopUp(){
	document.getElementById("cartelNoticias").style.visibility="hidden";
	document.getElementById("fondo_negro").style.visibility="hidden";
	document.getElementById("cartelNoticias").innerHTML=" ";
}
